version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.5
    commands:
      - terraform --version

  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init

  build:
    commands:
      - echo Running Terraform Plan...
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo Applying Terraform...
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
